# Copyright 2021. Huawei Technologies Co., Ltd. All rights reserved.

# Licensed under the Apache License, Version 2.0 (the "License")
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     https://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import warnings

HW_LOCATION_TYPE = set(["ACCESS_GATEWAY", "ADDRESS", "ADMINISTRATIVE_AREA_LEVEL_1", "ADMINISTRATIVE_AREA_LEVEL_2", "ADMINISTRATIVE_AREA_LEVEL_3", "ADMINISTRATIVE_AREA_LEVEL_4",
                        "ADMIN_FEATURE", "ADVENTURE_SPORTS_VENUE", "ADVENTURE_VEHICLE_TRAIL", "ADVERTISING_AND_MARKETING_COMPANY", "AFGHAN_RESTAURANT", "AFRICAN_RESTAURANT",
                        "AGRICULTURAL_SUPPLY_STORE", "AGRICULTURAL_TECHNOLOGY_COMPANY", "AGRICULTURE_BUSINESS", "AIRFIELD", "AIRLINE", "AIRLINE_ACCESS", "AIRPORT", "ALGERIAN_RESTAURANT",
                        "AMBULANCE_UNIT", "AMERICAN_RESTAURANT", "AMPHITHEATER", "AMUSEMENT_ARCADE", "AMUSEMENT_PARK", "AMUSEMENT_PLACE", "ANIMAL_SERVICE_STORE", "ANIMAL_SHELTER", "ANTIQUE_ART_STORE",
                        "APARTMENT", "AQUATIC_ZOO_MARINE_PARK", "ARABIAN_RESTAURANT", "ARBORETA_BOTANICAL_GARDENS", "ARCH", "ARGENTINEAN_RESTAURANT", "ARMENIAN_RESTAURANT", "ART_MUSEUM", "ART_SCHOOL",
                        "ASHRAM", "ASIAN_RESTAURANT", "ATHLETIC_STADIUM", "ATV_SNOWMOBILE_DEALER", "AUSTRALIAN_RESTAURANT", "AUSTRIAN_RESTAURANT", "AUTOMATIC_TELLER_MACHINE", "AUTOMOBILE_ACCESSORIES_SHOP",
                        "AUTOMOBILE_COMPANY", "AUTOMOBILE_MANUFACTURING_COMPANY", "AUTOMOTIVE", "AUTOMOTIVE_DEALER", "AUTOMOTIVE_GLASS_REPLACEMENT_SHOP", "AUTOMOTIVE REPAIR_SHOP", "BADMINTON_COURT",
                        "BAGS_LEATHERWEAR_SHOP", "BAKERY", "BANK", "BANQUET_ROOM", "BAR", "BARBECUE_RESTAURANT", "BASEBALL_FIELD", "BASKETBALL_COURT", "BASQUE_RESTAURANT", "BATTLEFIELD", "BAY", "BEACH",
                        "BEACH_CLUB", "BEAUTY_SALON", "BEAUTY_SUPPLY_SHOP", "BED_BREAKFAST_GUEST_HOUSES", "BELGIAN_RESTAURANT", "BETTING_STATION", "BICYCLE_PARKING_PLACE", "BICYCLE_SHARING_LOCATION",
                        "BILLIARDS_POOL_HALL", "BISTRO", "BLOOD_BANK", "BOATING_EQUIPMENT_ACCESSORIES_STORE", "BOAT_DEALER", "BOAT_FERRY", "BOAT_LAUNCHING_RAMP", "BODYSHOPS", "BOLIVIAN_RESTAURANT",
                        "BOOKSTORE", "BORDER_POST", "BOSNIAN_RESTAURANT", "BOWLING_FIELD", "BRAZILIAN_RESTAURANT", "BRIDGE", "BRIDGE_TUNNEL_ENGINEERING_COMPANY", "BRITISH_RESTAURANT", "BUDDHIST_TEMPLE",
                        "BUFFET", "BUILDING", "BULGARIAN_RESTAURANT", "BUNGALOW", "BURMESE_RESTAURANT", "BUSINESS", "BUSINESS_PARK", "BUSINESS_SERVICES_COMPANY", "BUS_CHARTER_RENTAL_COMPANY", "BUS_COMPANY",
                        "BUS_DEALER", "BUS_STOP", "CABARET", "CABINS_LODGES", "CABLE_TELEPHONE_COMPANY", "CAFE", "CAFETERIA", "CAFE_PUB", "CALIFORNIAN_RESTAURANT", "CAMBODIAN_RESTAURANT",
                        "CAMPING_GROUND", "CANADIAN_RESTAURANT", "CAPE", "CAPITAL", "CAPITAL_CITY", "CARAVAN_SITE", "CARGO_CENTER", "CARIBBEAN_RESTAURANT", "CARPET_FLOOR_COVERING_STORE",
                        "CAR_CLUB", "CAR_DEALER", "CAR_RENTAL", "CAR_RENTAL_COMPANY", "CAR_WASH", "CAR_WASH_SUB", "CASINO", "CATERING_COMPANY", "CAVE", "CD_DVD_VIDEO_RENTAL_STORE",
                        "CD_DVD_VIDEO_STORE", "CD_DVD_VIDEO_STORE_SUB", "CEMETERY", "CHALET", "CHEMICAL_COMPANY", "CHICKEN_RESTAURANT", "CHILDRENS_MUSEUM", "CHILD_CARE_FACILITY",
                        "CHILEAN_RESTAURANT", "CHINESE_MEDICINE_HOSPITAL", "CHINESE_RESTAURANT", "CHRISTMAS_HOLIDAY_STORE", "CHURCH", "CINEMA", "CINEMA_SUB", "CITIES", "CITY_CENTER",
                        "CITY_HALL", "CIVIC_COMMUNITY_CENTER", "CLEANING_SERVICE_COMPANY", "CLOTHING_ACCESSORIES_STORE", "CLUB_ASSOCIATION", "COACH_PARKING_AREA", "COACH_STATION",
                        "COCKTAIL_BAR", "COFFEE_SHOP", "COLLEGE_UNIVERSITY", "COLOMBIAN_RESTAURANT", "COMEDY_CLUB", "COMMERCIAL_BUILDING", "COMMUNITY_CENTER", "COMPANY",
                        "COMPUTER_AND_DATA_SERVICES_CORPORATION", "COMPUTER_SOFTWARE_COMPANY", "COMPUTER_STORE", "CONCERT_HALL", "CONDOMINIUM_COMPLEX", "CONSTRUCTION_COMPANY",
                        "CONSTRUCTION_MATERIAL_EQUIPMENT_SHOP", "CONSUMER_ELECTRONICS_STORE", "CONTINENT", "CONVENIENCE_STORE", "CORSICAN_RESTAURANT", "COTTAGE", "COUNTRY",
                        "COUNTY", "COUNTY_COUNCIL", "COURIER_DROP_BOX", "COURTHOUSE", "COVE", "CREOLE_CAJUN_RESTAURANT", "CREPERIE", "CRICKET_GROUND", "CUBAN_RESTAURANT", "CULINARY_SCHOOL",
                        "CULTURAL_CENTER", "CURRENCY_EXCHANGE", "CURTAIN_TEXTILE_STORE", "CYPRIOT_RESTAURANT", "CZECH_RESTAURANT", "DAM", "DANCE_STUDIO_SCHOOL",
                        "DANCING_CLUB", "DANISH_RESTAURANT", "DELICATESSEN_STORE", "DELIVERY_ENTRANCE", "DENTAL_CLINIC", "DEPARTMENT_STORE", "DHARMA_TEMPLE", "DINNER_THEATER",
                        "DISCOTHEQUE", "DIVERSIFIED_FINANCIAL_SERVICE_COMPANY", "DIVING_CENTER", "DOCK", "DOMINICAN_RESTAURANT", "DONGBEI_RESTAURANT", "DOUGHNUT_SHOP",
                        "DO_IT_YOURSELF_CENTERS", "DRIVE_IN_CINEMA", "DRIVE_THROUGH_BOTTLE_SHOP", "DRIVING_SCHOOL", "DRUGSTORE", "DRY_CLEANERS", "DUNE", "DUTCH_RESTAURANT",
                        "EARTHQUAKE_ASSEMBLY_POINT_", "EATING_DRINKING", "EDUCATION_INSTITUTION", "EGYPTIAN_RESTAURANT", "ELECTRICAL_APPLIANCE_STORE", "ELECTRICAL_APPLIANCE_STORE_SUB",
                        "ELECTRIC_VEHICLE_CHARGING_STATION", "ELECTRONICS_COMPANY", "ELECTRONICS_STORE", "EMBASSY", "EMERGENCY_ASSEMBLY_POINT", "EMERGENCY_MEDICAL_SERVICE_CENTER",
                        "EMERGENCY_ROOM", "ENGLISH_RESTAURANT", "ENTERTAINMENT_CABARET_LIVE", "ENTERTAINMENT_PLACE", "EQUIPMENT_RENTAL_COMPANY", "EROTIC_RESTAURANT", "ESTABLISHMENT",
                        "ETHIOPIAN_RESTAURANT", "EXCHANGE", "EXHIBITION_CONVENTION_CENTER", "EXOTIC_RESTAURANT", "FACTORY_OUTLETS", "FAIRGROUND", "FARM", "FARMER_MARKET",
                        "FAST_FOOD_RESTAURANT", "FERRY_TERMINAL", "FILIPINO_RESTAURANT", "FINNISH_RESTAURANT", "FIRE_ASSEMBLY_POINT", "FIRE_STATION_BRIGADE", "FISHING_HUNTING_AREA",
                        "FISH_STORE", "FITNESS_CLUB_CENTER", "FIVE_STAR_HOTEL", "FLATS_APARTMENT_COMPLEX", "FLOOD_ASSEMBLY_POINT", "FLORISTS", "FLYING_CLUB", "FONDUE_RESTAURANT",
                        "FOOD_DRINK_SHOP", "FOOD_MARKET", "FOOTBALL_FIELD", "FOREST_AREA", "FOUR_STAR_HOTEL", "FRENCH_RESTAURANT", "FUNERAL_SERVICE_COMPANY", "FURNITURE_ACCESSORIES_STORE",
                        "FURNITURE_STORE", "FUSION_RESTAURANT", "GALLERY", "GARDENING_CERVICE_CENTER", "GENERAL_AUTO_REPAIR_SERVICE_CENTER", "GENERAL_CITY", "GENERAL_CLINIC",
                        "GENERAL_HOSPITAL", "GENERAL_POST_OFFICE", "GEOCODE", "GEOGRAPHIC_FEATURE", "GERMAN_RESTAURANT", "GIFT_STORE", "GLASSWARE_CERAMIC_SHOP", "GLASS_WINDOW_STORE",
                        "GOLD_EXCHANGE", "GOLF_COURSE", "GOVERNMENT_OFFICE", "GOVERNMENT_PUBLIC_SERVICE", "GREEK_RESTAURANT", "GREENGROCERY", "GRILL", "GROCERY", "GUANGDONG_RESTAURANT",
                        "GURUDWARA", "HAIR_SALON_BARBERSHOP", "HAMBURGER_RESTAURANT", "HAMLET", "HARBOR", "HARDWARE_STORE", "HEALTHCARE_SERVICE_CENTER", "HEALTH_CARE",
                        "HELIPAD_HELICOPTER_LANDING", "HIGHWAY_EXIT", "HIGHWAY__ENTRANCE", "HIGH_SCHOOL", "HIKING_TRAIL", "HILL", "HINDU_TEMPLE", "HISTORICAL_PARK", "HISTORIC_SITE",
                        "HISTORY_MUSEUM", "HOBBY_SHOP", "HOCKEY_CLUB", "HOCKEY_FIELD", "HOLIDAY_HOUSE_RENTAL", "HOME_APPLIANCE_REPAIR_COMPANY", "HOME_GOODS_STORE", "HORSE_RACING_TRACK",
                        "HORSE_RIDING_FIELD", "HORSE_RIDING_TRAIL", "HORTICULTURE_COMPANY", "HOSPITAL_FOR_WOMEN_AND_CHILDREN", "HOSPITAL_POLYCLINIC", "HOSTEL", "HOTEL",
                        "HOTELS_WITH_LESS_THAN_TWO_STARS", "HOTEL_MOTEL", "HOT_POT_RESTAURANT", "HOUSEHOLD_APPLIANCE_STORE", "HUNAN_RESTAURANT", "HUNGARIAN_RESTAURANT",
                        "ICE_CREAM_PARLOR", "ICE_HOCKEY_RINK", "ICE_SKATING_RINK", "IMPORTANT_TOURIST_ATTRACTION", "IMPORT_AND_EXPORT_DISTRIBUTION_COMPANY", "INDIAN_RESTAURANT",
                        "INDONESIAN_RESTAURANT", "INDUSTRIAL_BUILDING", "INFORMAL_MARKET", "INSURANCE_COMPANY", "INTERCITY_RAILWAY_STATION", "INTERNATIONAL_ORGANIZATION",
                        "INTERNATIONAL_RAILWAY_STATION", "INTERNATIONAL_RESTAURANT", "INTERNET_CAFE", "INVESTMENT_CONSULTING_FIRM", "IRANIAN_RESTAURANT", "IRISH_RESTAURANT",
                        "ISLAND", "ISRAELI_RESTAURANT", "ITALIAN_RESTAURANT", "JAIN_TEMPLE", "JAMAICAN_RESTAURANT", "JAPANESE_RESTAURANT", "JAZZ_CLUB", "JEWELRY_CLOCK_AND_WATCH_SHOP",
                        "JEWISH_RESTAURANT", "JUNIOR_COLLEGE_COMMUNITY_COLLEGE", "KARAOKE_CLUB", "KITCHEN_AND_SANITATION_STORE", "KOREAN_RESTAURANT", "KOSHER_RESTAURANT",
                        "LAGOON", "LAKESHORE", "LANGUAGE_SCHOOL", "LATIN_AMERICAN_RESTAURANT", "LAUNDRY", "LEBANESE_RESTAURANT", "LEGAL_SERVICE_COMPANY", "LEISURE",
                        "LEISURE_CENTER", "LIBRARY", "LIGHTING_STORE", "LOADING_ZONE", "LOCAL_POST_OFFICE", "LOCAL_SPECIALTY_STORE", "LODGING_LIVING_ACCOMMODATION", "LOTTERY_SHOP",
                        "LUXEMBOURGIAN_RESTAURANT", "MACROBIOTIC_RESTAURANT", "MAGHRIB_RESTAURANT", "MAIL_PACKAGE_FREIGHT_DELIVERY_COMPANY", "MALTESE_RESTAURANT", "MANUFACTURING_COMPANY",
                        "MANUFACTURING_FACTORY", "MARINA", "MARINA_SUB", "MARINE_ELECTRONIC_EQUIPMENT_STORE", "MARKET", "MARSH_SWAMP_VLEI", "MAURITIAN_RESTAURANT", "MAUSOLEUM_GRAVE", "MEAT_STORE",
                        "MECHANICAL_ENGINEERING_COMPANY", "MEDIA_COMPANY", "MEDICAL_CLINIC", "MEDICAL_SUPPLIES_EQUIPMENT_STORE", "MEDITERRANEAN_RESTAURANT", "MEMORIAL", "MEMORIAL_PLACE", "METRO",
                        "MEXICAN_RESTAURANT", "MICROBREWERY_BEER_GARDEN", "MIDDLE_EASTERN_RESTAURANT", "MIDDLE_SCHOOL", "MILITARY_AUTHORITY", "MILITARY_BASE", "MINERAL_COMPANY",
                        "MINERAL_HOT_SPRINGS", "MISCELLANEOUS", "MOBILE_PHONE_STORE", "MONGOLIAN_RESTAURANT", "MONUMENT", "MORMON_CHURCH", "MOROCCAN_RESTAURANT", "MOSQUE",
                        "MOTEL", "MOTORCYCLE_DEALER", "MOTORCYCLE_REPAIR_SHOP", "MOTORING_ORGANIZATION_OFFICE", "MOTORSPORT_VENUE", "MOUNTAIN_BIKE_TRAIL", "MOUNTAIN_PASS",
                        "MOUNTAIN_PEAK", "MOVING_STORAGE_COMPANY", "MULTIPURPOSE_STADIUM", "MUSEUM", "MUSICAL_INSTRUMENT_STORE", "MUSIC_CENTER", "MUSSEL_RESTAURANT", "NAIL_SALON",
                        "NAMED_INTERSECTION", "NATIONAL_ORGANIZATION", "NATIONAL_RAILWAY_STATION", "NATIVE_RESERVATION", "NATURAL_ATTRACTION", "NATURAL_ATTRACTION_TOURIST", "NEIGHBORHOOD",
                        "NEPALESE_RESTAURANT", "NETBALL_COURT", "NEWSAGENTS_AND_TOBACCONISTS", "NIGHTLIFE", "NIGHT_CLUB", "NON_GOVERNMENTAL_ORGANIZATION", "NORWEGIAN_RESTAURANT", "NURSING_HOME",
                        "OASIS", "OBSERVATION_DECK", "OBSERVATORY", "OEM", "OFFICE_EQUIPMENT_STORE", "OFFICE_SUPPLY_SERVICES_STORE", "OIL_NATURAL_GAS_COMPANY", "OPERA", "OPTICIANS",
                        "ORDER_1_AREA_GOVERNMENT_OFFICE", "ORDER_1_AREA_POLICE_STATION", "ORDER_2_AREA_GOVERNMENT_OFFICE", "ORDER_3_AREA_GOVERNMENT_OFFICE", "ORDER_4_AREA_GOVERNMENT_OFFICE",
                        "ORDER_5_AREA_GOVERNMENT_OFFICE", "ORDER_6_AREA_GOVERNMENT_OFFICE", "ORDER_7_AREA_GOVERNMENT_OFFICE", "ORDER_8_AREA_GOVERNMENT_OFFICE", "ORDER_8_AREA_POLICE_STATION",
                        "ORDER_9_AREA_GOVERNMENT_OFFICE", "ORDER_9_AREA_POLICE_STATION", "ORGANIC_RESTAURANT", "ORGANIZATION", "ORIENTAL_RESTAURANT", "OUTLETS", "PAGODA", "PAINTING_DECORATING_STORE",
                        "PAKISTANI_RESTAURANT", "PAN", "PARK", "PARKING_GARAGE", "PARKING_LOT", "PARKING_LOT_SUB", "PARKWAY", "PARK_AND_RECREATION_AREA", "PARK_RIDE", "PASSENGER_TRANSPORT_TICKET_OFFICE",
                        "PAWN_SHOP", "PEDESTRIAN_SUBWAY", "PERSONAL_CARE_INSTITUTION", "PERSONAL_SERVICE_CENTER", "PERUVIAN_RESTAURANT", "PETROL_STATION", "PET_STORE", "PET_SUPPLY_STORE",
                        "PHARMACEUTICAL_COMPANY", "PHARMACY", "PHOTOCOPY_SHOP", "PHOTOGRAPHIC_EQUIPMENT_STORE", "PHOTO_SHOP", "PHYSIOTHERAPY_CLINIC", "PICK_UP_AND_RETURN_POINT", "PICNIC_AREA",
                        "PIZZA_RESTAURANT", "PLACE_OF_WORSHIP", "PLAIN_FLAT", "PLANETARIUM", "PLATEAU", "POLICE_STATION", "POLISH_RESTAURANT", "POLYNESIAN_RESTAURANT", "PORTUGUESE_RESTAURANT",
                        "PORT_WAREHOUSE", "POSTAL_CODE", "POST_OFFICE", "PRESCHOOL", "PRESERVED_AREA", "PRIMARY_SCHOOL", "PRISON", "PRIVATE_AUTHORITY", "PRIVATE_CLUB", "PRODUCER_COMPANY",
                        "PROTECTED_AREA", "PROVENÇAL_RESTAURANT", "PUB", "PUBLIC_AMENITY", "PUBLIC_AUTHORITY", "PUBLIC_CALL_BOX", "PUBLIC_HEALTH_TECHNOLOGY_COMPANY", "PUBLIC_MARKET",
                        "PUBLIC_RESTROOM", "PUBLIC_TRANSPORT_STOP", "PUBLISHING_TECHNOLOGY_COMPANY", "PUB_FOOD", "QUARRY", "RACE_TRACK", "RAILWAY_SIDING", "RAILWAY_STATION", "RAIL_FERRY", "RAPIDS",
                        "REAL_ESTATE_AGENCY_COMPANY", "REAL_ESTATE_AGENCY_SHOP", "RECREATIONAL_SITE", "RECREATIONAL_VEHICLE_DEALER", "RECREATION_AREA", "RECYCLING_SHOP", "REEF",
                        "REGIONS", "REPAIR_SHOP", "RESEARCH_INSTITUTE", "RESERVOIR", "RESIDENTIAL_ACCOMMODATION", "RESIDENTIAL_ESTATE", "RESORT", "RESTAURANT", "RESTAURANT_AREA", "REST_AREA",
                        "REST_CAMPS", "RETAIL_OUTLETS", "RETIREMENT_COMMUNITY", "RIDGE", "RIVER_CROSSING", "ROADSIDE", "ROAD_RESCUE_POINT", "ROCKS", "ROCK_CLIMBING_TRAIL",
                        "ROMANIAN_RESTAURANT", "ROUTE", "RUGBY_GROUND", "RUSSIAN_RESTAURANT", "SALAD_BAR", "SANDWICH_RESTAURANT", "SAUNA_SOLARIUM_MASSAGE_CENTER",
                        "SAVINGS_INSTITUTION", "SAVOYAN_RESTAURANT", "SCANDINAVIAN_RESTAURANT", "SCENIC_RIVER_AREA", "SCHOOL", "SCHOOL_BUS_SERVICE_COMPANY", "SCIENCE_MUSEUM",
                        "SCOTTISH_RESTAURANT", "SEAFOOD_RESTAURANT", "SEASHORE", "SECURITY_GATE", "SECURITY_STORE", "SENIOR_HIGH_SCHOOL", "SERVICE_COMPANY", "SHANDONG_RESTAURANT",
                        "SHANGHAI_RESTAURANT", "SHINTO_SHRINE", "SHOOTING_RANGE", "SHOP", "SHOPPING", "SHOPPING_CENTER", "SHOPPING_SERVICE_CENTER", "SICHUAN_RESTAURANT", "SICILIAN_RESTAURANT",
                        "SKI_LIFT", "SKI_RESORT", "SLAVIC_RESTAURANT", "SLOVAK_RESTAURANT", "SNACKS", "SNOOKER_POOL_BILLIARD_HALL", "SOCCER_FIELD", "SOUL_FOOD_RESTAURANT",
                        "SOUP_RESTAURANT", "SPA", "SPANISH_RESTAURANT", "SPECIALIST_CLINIC", "SPECIALIZED_HOSPITAL", "SPECIALTY_FOOD_STORE", "SPECIALTY_STORE", "SPECIAL_SCHOOL",
                        "SPORT", "SPORTS_CENTER", "SPORTS_CENTER_SUB", "SPORTS_SCHOOL", "SPORTS_STORE", "SQUASH_COURT", "STADIUM", "STAMP_SHOP", "STATION_ACCESS", "STATUE", "STEAK_HOUSE",
                        "STOCK_EXCHANGE", "STORE", "STREET_ADDRESS", "SUDANESE_RESTAURANT", "SUPERMARKET_HYPERMARKET", "SURINAMESE_RESTAURANT", "SUSHI_RESTAURANT", "SWEDISH_RESTAURANT",
                        "SWIMMING_POOL", "SWISS_RESTAURANT", "SYNAGOGUE", "SYRIAN_RESTAURANT", "TABLE_TENNIS_HALL", "TAILOR_SHOP", "TAIWANESE_RESTAURANT", "TAKE_AWAY_RESTAURANT",
                        "TAPAS_RESTAURANT", "TAXI_LIMOUSINE_SHUTTLE_SERVICE_COMPANY", "TAXI_STAND", "TAX_SERVICE_COMPANY", "TEA_HOUSE", "TECHNICAL_SCHOOL", "TELECOMMUNICATIONS_COMPANY", "TEMPLE", "TENNIS_COURT",
                        "TEPPANYAKKI_RESTAURANT", "TERMINAL", "THAI_RESTAURANT", "THEATER", "THEATER_SUB", "THEMED_SPORTS_HALL", "THREE_STAR_HOTEL", "TIBETAN_RESTAURANT",
                        "TIRE_REPAIR_SHOP", "TOILET", "TOLL_GATE", "TOURISM", "TOURIST_INFORMATION_OFFICE", "TOWER", "TOWN", "TOWNHOUSE_COMPLEX", "TOWN_GOVERNMENT",
                        "TOYS_AND_GAMES_STORE", "TRAFFIC", "TRAFFIC_CONTROL_DEPARTMENT", "TRAFFIC_LIGHT", "TRAFFIC_MANAGEMENT_BUREAU", "TRAFFIC_SIGN", "TRAFFIC_SIGNAL", "TRAILHEAD",
                        "TRAIL_SYSTEM", "TRAM_STOP", "TRANSPORT", "TRANSPORTATION_COMPANY", "TRANSPORT__CENTER", "TRAVEL_AGENCY", "TRUCK_DEALER", "TRUCK_PARKING_AREA", "TRUCK_REPAIR_SHOP",
                        "TRUCK_STOP", "TRUCK_WASH", "TSUNAMI_ASSEMBLY_POINT", "TUNISIAN_RESTAURANT", "TUNNEL", "TURKISH_RESTAURANT", "UNRATED_HOTEL", "URUGUAYAN_RESTAURANT", "USED_CAR_DEALER",
                        "VALLEY", "VAN_DEALER", "VARIETY_STORE", "VEGETARIAN_RESTAURANT", "VENEZUELAN_RESTAURANT", "VETERINARY_CLINIC", "VIDEO_ARCADE_GAMING_ROOM", "VIETNAMESE_RESTAURANT",
                        "VILLA", "VOCATIONAL_TRAINING_SCHOOL", "VOLCANIC_ERUPTION_ASSEMBLY_POINT", "WAREHOUSE_SUPERMARKET", "WATER_HOLE", "WATER_SPORTS_CENTER", "WEDDING_SERVICE_COMPANY",
                        "WEIGH_SCALES", "WEIGH_STATION", "WEIGH_STATION_SUB", "WELFARE_ORGANIZATION", "WELL", "WELSH_RESTAURANT", "WESTERN_RESTAURANT", "WILDERNESS_AREA", "WILDLIFE_PARK",
                        "WINERY", "WINERY_TOURIST", "WINE_BAR", "WINE_SPIRITS_STORE", "WINTER_SPORT_AREA", "YACHT_BASIN", "YOGURT_JUICE_BAR", "ZOO", "ZOO_ARBORETA_BOTANICAL_GARDEN"])

LOCATION_TYPE = set(['ACCOUNTING', ',ADDRESS', 'ADMINISTRATIVE_AREA_LEVEL_1',
                     'ADMINISTRATIVE_AREA_LEVEL_2', 'ADMINISTRATIVE_AREA_LEVEL_3', 'ADMINISTRATIVE_AREA_LEVEL_4', 'ADMINISTRATIVE_AREA_LEVEL_5',
                     'AIRPORT', 'AMUSEMENT_PARK', 'AQUARIUM', 'ARCHIPELAGO', 'ART_GALLERY', 'ATM', 'BAKERY',
                     'BANK', 'BAR', 'BEAUTY_SALON', 'BICYCLE_STORE', 'BOOK_STORE', 'BOWLING_ALLEY', 'BUS_STATION', 'CAFE',
                     'CAMPGROUND', 'CAPITAL', 'CAPITAL_CITY', 'CAR_DEALER', 'CAR_RENTAL', 'CAR_REPAIR', 'CAR_WASH',
                     'CASINO', 'CEMETERY', 'CHURCH', 'CITIES', 'CITY_HALL', 'CLOTHING_STORE', 'COLLOQUIAL_AREA',
                     'CONVENIENCE_STORE', 'CONTINENT', 'COUNTRY', 'COURTHOUSE', 'DENTIST', 'DEPARTMENT_STORE', 'DOCTOR',
                     'DRUGSTORE', 'ELECTRICIAN', 'ELECTRONICS_STORE', 'EMBASSY', 'ESTABLISHMENT', 'FINANCE', 'FIRE_STATION',
                     'FLOOR', 'FLORIST', 'FOOD', 'FUNERAL_HOME', 'FURNITURE_STORE', 'GAS_STATION', 'GENERAL_CITY',
                     'GENERAL_CONTRACTOR', 'GEOCODE', 'GROCERY_OR_SUPERMARKET', 'GYM', 'HAMLET', 'HAIR_CARE', 'HARDWARE_STORE',
                     'HEALTH', 'HINDU_TEMPLE', 'HOME_GOODS_STORE', 'HOSPITAL', 'INSURANCE_AGENCY', 'INTERSECTION',
                     'JEWELRY_STORE', 'LAUNDRY', 'LAWYER', 'LIBRARY', 'LIGHT_RAIL_STATION', 'LIQUOR_STORE', 'LOCALITY',
                     'LOCAL_GOVERNMENT_OFFICE', 'LOCKSMITH', 'LODGING', 'MEAL_DELIVERY', 'MEAL_TAKEAWAY', 'MOSQUE'
                     'MOVIE_RENTAL', 'MOVIE_THEATER', 'MOVING_COMPANY', 'MUSEUM', 'NATURAL_FEATURE', 'NEIGHBORHOOD',
                     'NIGHT_CLUB', 'OTHER', 'PAINTER', 'PARK', 'PARKING', 'PET_STORE', 'PHARMACY', 'PHYSIOTHERAPIST'
                     'PLACE_OF_WORSHIP', 'PLUMBER', 'POINT_OF_INTEREST', 'POLICE',
                     'POLITICAL', 'POSTAL_CODE', 'POSTAL_CODE_PREFIX', 'POSTAL_CODE_SUFFIX', 'POSTAL_TOWN',
                     'POST_BOX', 'POST_OFFICE', 'PREMISE', 'PRIMARY_SCHOOL', 'REAL_ESTATE_AGENCY', 'REGION', 'REGIONS',
                     'RESTAURANT', 'ROOFING_CONTRACTOR', 'ROOM', 'ROUTE', 'RV_PARK', 'SCHOOL', 'SECONDARY_SCHOOL', 'SHOE_STORE',
                     'SHOPPING_MALL', 'SPA', 'STADIUM', 'STORAGE', 'STORE', 'STREET_ADDRESS', 'STREET_NUMBER', 'SUBLOCALITY',
                     'SUBLOCALITY_LEVEL_1', 'SUBLOCALITY_LEVEL_2', 'SUBLOCALITY_LEVEL_3', 'SUBLOCALITY_LEVEL_4', 'SUBLOCALITY_LEVEL_5',
                     'SUBPREMISE', 'SUBWAY_STATION', 'SUPERMARKET', 'SYNAGOGUE', 'TAXI_STAND', 'TOURIST_ATTRACTION',
                     'TOWN', 'TOWN_SQUARE', 'TRAIN_STATION', 'TRANSIT_STATION', 'TRAVEL_AGENCY', 'UNIVERSITY', 'VETERINARY_CARE', 'ZOO'])


def is_hw_location_exists(hw_location):
    return hw_location in HW_LOCATION_TYPE


def is_location_exists(location):
    return location in LOCATION_TYPE


def warn_poi_not_exists(poi):
    if poi not in LOCATION_TYPE:
        warnings.warn('Given poi not exists.',
                      ResourceWarning, stacklevel=2)


def warn_hw_poi_not_exists(hw_poi):
    if hw_poi not in HW_LOCATION_TYPE:
        warnings.warn('Given hw poi not exists.',
                      ResourceWarning, stacklevel=2)
